// src/utils/shopItems.js

export const shopItems = [
  {
    id: "health_potion_consumable",
    name: "Major Health Potion",
    cost: 1,
    effect: "inventoryItem",
    details: "healthPotion",
    amount: 25,
    description: "Consumable. Recovers 25 HP when used from inventory.",
  },
    {
    name: "Minor Health Potion", 
    cost: 1,
    effect: "inventoryItem",
    amount: 10,
    details: "minorHealthPotion",
    description: "Restores 10 HP.",
  },
  {
    id: "whetstone",
    name: "Whetstone",
    cost: 1,
    effect: "weapon",
    amount: 1,
    description: "Permanently increases your Weapon Damage by 1.",
  },
  {
    id: "sturdy_buckler",
    name: "Sturdy Buckler",
    cost: 1,
    effect: "shield",
    amount: 1,
    description: "Permanently increases your Defense Bonus by 1.",
  },
  {
    id: "tome_knowledge",
    name: "Tome of Knowledge",
    cost: 1,
    effect: "special",
    amount: 1,
    description: "Grants +1 Class Ability Charge.",
  },
  {
    id: "arcane_compass",
    name: "Arcane Compass",
    cost: 1,
    effect: "inventoryItem",
    details: "compass",
    description: "Skips you to a random non-start/end article. Consumable.",
  },
  {
    id: "invisibility_cloak",
    name: "Cloak of Invisibility",
    cost: 1,
    effect: "inventoryItem",
    details: "invisibilityCloak",
    description: "Consumable. Avoids non-boss encounters for 10 clicks.",
  },
  {
    id: "stick_item",
    name: "A Cool Stick That I Found",
    cost: 1,
    effect: "inventoryItem",
    details: "stickItem",
    description: "Doesn't do much. It's just a cool stick that I found.",
  },
  {
    id: "herbal_heal_item",
    name: "Herbal Poultice",
    cost: 1,
    effect: "inventoryItem",
    details: "herbalPoultice",
    amount: 1,
    durationClicks: 30,
    maxHeal: 30,
  },
  {
    id: "bark_tea_consumable",
    name: "Bark Tea",
    cost: 1,
    effect: "inventoryItem",
    details: "barkTea",
    amount: 10,
  },
  {
    id: "french_onion_soup_consumable",
    name: "French Onion Soup",
    cost: 1,
    effect: "inventoryItem",
    details: "frenchOnionSoup",
    healAmount: 15,
    specialAmount: 1,
  },
  {
    id: "antidote_consumable",
    name: "Antidote",
    cost: 1,
    effect: "inventoryItem",
    details: "antidote",
    description:
      "A potent concoction that cleanses the body of toxins, removing all poison effects.",
  },
  {
    id: "smoke_bomb_consumable",
    name: "Smoke Bomb",
    cost: 1,
    effect: "inventoryItem",
    details: "smokeBomb",
    description:
      "Creates a thick cloud, allowing you to escape from non-boss combat.",
  },
  {
    id: "adventurers_rations_consumable",
    name: "Adventurer's Rations",
    cost: 1,
    effect: "inventoryItem",
    details: "adventurersRations",
    healAmount: 7,
    blurCure: true,
    description:
      "Simple, wholesome provisions that restore a little health and clear the mind.",
  },
  {
    id: "amulet_of_shared_suffering",
    name: "Amulet of Shared Suffering",
    cost: 1,
    effect: "inventoryItem",
    details: "sharedSufferingAmulet",
    description:
      "Combat only. Deals 50 damage to the enemy and 25 damage to you. Consumed upon use.",
    enemyDamage: 50,
    playerDamage: 25,
    combatOnly: true,
  },
];
