// src/utils/shopItems.js

export const shopItems = [
  {
    id: "stick_item",
    name: "A Cool Stick That I Found",
    cost: 1,
    effect: "inventoryItem",
    details: "stickItem",
    description: "Doesn't do much. It's just a cool stick that I found.",
    haikuOne: "Just a common branch",
    haikuTwo: "Yet in its form, comfort found",
    haikuThree: "A small, perfect thing.",
  },
  {
    id: "cooler_stick_item",
    name: "A Cooler Stick That I Found",
    cost: 100,
    effect: "inventoryItem",
    details: "coolerStickItem",
    description: "An upgrade to your original stick. Grants +2 to all combat dice rolls while in your inventory.",
    haikuOne: "A finer branch, straight",
    haikuTwo: "Two fortune added to rolls",
    haikuThree: "The stick grows in power.",
  },
  {
    id: "even_cooler_stick_item",
    name: "An Even Cooler Stick That I Found",
    cost: 300,
    effect: "inventoryItem",
    details: "evenCoolerStickItem",
    description: "An even more powerful upgrade. Grants an additional +3 to all combat dice rolls while in your inventory.",
    haikuOne: "Ancient wood, etched runes",
    haikuTwo: "Three more fortune bends to will",
    haikuThree: "The stick ascends now.",
  },
  {
    id: "adventurers_rations_consumable",
    name: "Adventurer's Rations",
    cost: 8,
    effect: "inventoryItem",
    details: "adventurersRations",
    healAmount: 7,
    blurCure: true,
    description:
      "Simple, wholesome provisions that restore 7 HP and clear the mind of any blur. Consumable.",
    haikuOne: "Dry bread, hard cheese, cured",
    haikuTwo: "The journey's fuel, mind clears bright",
    haikuThree: "New day, spirit keen.",
  },
  {
    name: "Minor Health Potion",
    cost: 8,
    effect: "inventoryItem",
    amount: 10,
    details: "minorHealthPotion",
    description: "Restores 10 HP.",
    haikuOne: "Whisper of green light",
    haikuTwo: "A fragile strength, briefly gained",
    haikuThree: "Shadows then recede.",
  },
  {
    id: "bark_tea_consumable",
    name: "Bark Tea",
    cost: 10,
    effect: "inventoryItem",
    details: "barkTea",
    description: "A bitter brew with minor healing properties, restores 12 HP.",
    amount: 12,
    haikuOne: "Wild roots steeped so dark",
    haikuTwo: "A forest tang, small comfort",
    haikuThree: "Faint warmth starts to bloom.",
  },
  {
    id: "smoke_bomb_consumable",
    name: "Smoke Bomb",
    cost: 15,
    effect: "inventoryItem",
    details: "smokeBomb",
    description:
      "Creates a thick cloud, allowing you to escape from non-boss combat.",
    haikuOne: "Sudden cloud expands",
    haikuTwo: "Enemies lost, shadows call",
    haikuThree: "Freedom takes swift flight.",
  },
  {
    id: "antidote_consumable",
    name: "Antidote",
    cost: 20,
    effect: "inventoryItem",
    details: "antidote",
    description:
      "A potent concoction that cleanses the body of toxins, removing all poison effects.",
    haikuOne: "Poison's cold embrace",
    haikuTwo: "A burning sip, darkness yields",
    haikuThree: "Clean blood flows anew.",
  },
  {
    id: "lucky_coin",
    name: "Lucky Coin",
    cost: 20,
    effect: "inventoryItem",
    details: "luckyCoin",
    description: "Guarantees your next Flee attempt succeeds. Combat only. Consumable.",
    combatOnly: true,
    haikuOne: "Heads and fate aligns",
    haikuTwo: "Fortune tips the scale tonight",
    haikuThree: "Swift legs find the door.",
  },
  {
    id: "health_potion_consumable",
    name: "Major Health Potion",
    cost: 20,
    effect: "inventoryItem",
    details: "healthPotion",
    amount: 25,
    description: "Consumable. Recovers 25 HP when used from inventory.",
    haikuOne: "A Strong, Red Potion",
    haikuTwo: "Used to regain heart and life",
    haikuThree: "Life's flame burns anew.",
  },
  {
    id: "french_onion_soup_consumable",
    name: "French Onion Soup",
    cost: 25,
    effect: "inventoryItem",
    details: "frenchOnionSoup",
    healAmount: 15,
    specialAmount: 1,
    description: "Restores 15 HP and 1 special ability charge. Consumable.",
    haikuOne: "Golden broth, onions",
    haikuTwo: "Richness warms the weary soul",
    haikuThree: "Strength gently returns.",
  },
  {
    id: "tome_knowledge",
    name: "Tome of Knowledge",
    cost: 25,
    effect: "special",
    amount: 2,
    description: "Grants +2 Class Ability Charge.",
    haikuOne: "Dusty pages turn",
    haikuTwo: "Old secrets whisper, mind awakes",
    haikuThree: "New paths now unfold.",
  },
  {
    id: "venom_vial",
    name: "Venom Vial",
    cost: 25,
    effect: "inventoryItem",
    details: "venomVial",
    description: "Poisons the enemy for 4 turns, dealing 3 damage per turn. Combat only. Consumable.",
    combatOnly: true,
    poisonDamage: 3,
    poisonDuration: 4,
    haikuOne: "Green glass, bitter death",
    haikuTwo: "Drop by drop, life seeps away",
    haikuThree: "Slow rot claims the foe.",
  },
  {
    id: "ward_stone",
    name: "Ward Stone",
    cost: 25,
    effect: "inventoryItem",
    details: "wardStone",
    description: "Suppresses non-boss encounters for 5 clicks. Weaker than the Cloak. Consumable.",
    haikuOne: "Rune-carved pebble hums",
    haikuTwo: "Shadows part, threats turn away",
    haikuThree: "Five steps, peace holds fast.",
  },
  {
    id: "flash_powder",
    name: "Flash Powder",
    cost: 30,
    effect: "inventoryItem",
    details: "flashPowder",
    description: "Stuns the enemy for 1 turn, causing them to skip their attack. Combat only. Consumable.",
    combatOnly: true,
    haikuOne: "Sudden blinding flash",
    haikuTwo: "Eyes seared white, the world goes still",
    haikuThree: "Breath held, strike now falls.",
  },
  {
    id: "serrated_dagger",
    name: "Serrated Dagger",
    cost: 30,
    effect: "inventoryItem",
    details: "serratedDagger",
    description: "Your next attack causes the enemy to Bleed for 2 turns (1 damage/turn). Combat only. Consumable.",
    combatOnly: true,
    haikuOne: "Jagged edge bites deep",
    haikuTwo: "Wound reopens each step taken",
    haikuThree: "Red trail marks the way.",
  },
  {
    id: "encounter_beacon",
    name: "Encounter Beacon",
    cost: 35,
    effect: "inventoryItem",
    details: "encounterBeacon",
    description: "Forces your next random encounter to be a friendly NPC. Consumable.",
    haikuOne: "Lantern swings in dark",
    haikuTwo: "A friendly face answers light",
    haikuThree: "Warmth where cold once crept.",
  },
  {
    id: "warding_shield",
    name: "Warding Shield",
    cost: 35,
    effect: "inventoryItem",
    details: "wardingShield",
    description: "Halves incoming enemy attack damage for the next 3 hits. Combat only. Consumable.",
    combatOnly: true,
    haikuOne: "Arm raised, blow deflects",
    haikuTwo: "Three strikes dulled by iron will",
    haikuThree: "Pain fades, you still stand.",
  },
  {
    id: "herbal_heal_item",
    name: "Herbal Poultice",
    cost: 40,
    effect: "inventoryItem",
    details: "herbalPoultice",
    amount: 1,
    durationClicks: 30,
    maxHeal: 30,
    description: "Heals 1 HP per click for up to 30 clicks. Consumable.",
    haikuOne: "Green leaves softly press",
    haikuTwo: "Life's slow balm, pain starts to fade",
    haikuThree: "Whispers of new skin.",
  },
  {
    id: "sturdy_buckler",
    name: "Sturdy Buckler",
    cost: 40,
    effect: "shield",
    amount: 1,
    description: "Permanently increases your Defense Bonus by 1.",
    haikuOne: "Oak and iron stand",
    haikuTwo: "A defiant wall against blows",
    haikuThree: "Safe behind the guard.",
  },
  {
    id: "whetstone",
    name: "Whetstone",
    cost: 40,
    effect: "weapon",
    amount: 1,
    description: "Permanently increases your Weapon Damage by 1.",
    haikuOne: "Steel cries on the stone",
    haikuTwo: "A hungry gleam now sharpens bright",
    haikuThree: "Fate awaits the cut.",
  },
      {
    id: "gold_pouch",
    name: "Gold Pouch",
    cost: 50,
    effect: "inventoryItem",
    details: "goldPouch",
    description: "Passively accumulates 1 gold per click. Use to collect the stored gold. Consumable.",
    haikuOne: "Leather purse, soft weight",
    haikuTwo: "Each step drops a coin inside",
    haikuThree: "Wealth waits to be claimed.",
  },
  {
    id: "invisibility_cloak",
    name: "Cloak of Invisibility",
    cost: 50,
    effect: "inventoryItem",
    details: "invisibilityCloak",
    description: "Grants invisibility from non-boss encounters for 10 clicks. Consumable.",
    haikuOne: "Flicker of false air",
    haikuTwo: "Through enemy lines, unseen",
    haikuThree: "Ghost steps softly glide.",
  },
  {
    id: "amulet_of_shared_suffering",
    name: "Amulet of Shared Suffering",
    cost: 80,
    effect: "inventoryItem",
    details: "sharedSufferingAmulet",
    description:
      "Combat only. Deals 50 damage to the enemy and 25 damage to you. Consumed upon use.",
    enemyDamage: 50,
    playerDamage: 25,
    combatOnly: true,
    haikuOne: "Dark pact, shared anguish",
    haikuTwo: "Wounds exchanged, a grim balance",
    haikuThree: "Echoes of triumph.",
  },
  {
    id: "arcane_compass",
    name: "Arcane Compass",
    cost: 100,
    effect: "inventoryItem",
    details: "compass",
    description: "Skips you to a random non-start/end article. Consumable.",
    haikuOne: "Glyphs on silver gleam",
    haikuTwo: "Worlds unseen, a random twist",
    haikuThree: "Fate's new road unfurled.",
  },
];
