// src/utils/shopItems.js

export const shopItems = [
  {
    id: "health_potion_consumable",
    name: "Health Potion",
    cost: 15,
    effect: "inventoryItem",
    details: "healthPotion",
    amount: 30,
    description: "Consumable. Recovers 30 HP when used from inventory.",
  },
  {
    id: "whetstone",
    name: "Whetstone",
    cost: 20,
    effect: "weapon",
    amount: 1,
    description: "Permanently increases your Weapon Damage by 1.",
  },
  {
    id: "sturdy_buckler",
    name: "Sturdy Buckler",
    cost: 20,
    effect: "shield",
    amount: 1,
    description: "Permanently increases your Defense Bonus by 1.",
  },
  {
    id: "tome_knowledge",
    name: "Tome of Knowledge",
    cost: 15,
    effect: "special",
    amount: 1,
    description: "Grants +1 Class Ability Charge.",
  },
  {
    id: "arcane_compass",
    name: "Arcane Compass",
    cost: 25,
    effect: "inventoryItem",
    details: "compass",
    description: "Skips you to a random non-start/end article. Consumable.",
  },
  {
    id: "invisibility_cloak",
    name: "Cloak of Invisibility",
    cost: 1,
    effect: "inventoryItem",
    details: "invisibilityCloak",
    description: "Consumable. Avoids non-boss encounters for 10 clicks.",
  },
  {
    id: "stick_item",
    name: "A Cool Stick That I Found",
    cost: 1,
    effect: "inventoryItem",
    details: "stickItem",
    description: "Doesn't do much. It's just a cool stick that I found.",
  },
  {
    id: "herbal_heal_item",
    name: "Herbal Poultice",
    cost: 1,
    effect: "inventoryItem",
    details: "herbalPoultice",
    amount: 1,
    durationClicks: 30,
    maxHeal: 30,
    description: "A hearty soup that restores 10 HP and 1 special use.",
  },
  {
    id: "bark_tea_consumable",
    name: "Bark Tea",
    cost: 1,
    effect: "inventoryItem",
    details: "barkTea",
    amount: 8,
    description: "A hearty soup that restores 10 HP and 1 special use.",
  },
    {
    id: "french_onion_soup_consumable",
    name: "French Onion Soup",
    cost: 25,
    effect: "inventoryItem",
    details: "frenchOnionSoup",
    healAmount: 10,
    specialAmount: 1, 
    description: "A hearty soup that restores 10 HP and 1 special use.",
  },
];
